# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mov-13',
                'doc_host': 'https://daveramseymusic.github.io',
                'git_url': 'https://github.com/daveramseymusic/mov-13',
                'lib_path': 'mov_13'},
  'syms': {'mov_13.core': {'mov_13.core.foo': ('core.html#foo', 'mov_13/core.py')}}}