# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mov-13',
                'doc_host': 'https://daveramseymusic.github.io',
                'git_url': 'https://github.com/daveramseymusic/mov-13',
                'lib_path': 'mov_13'},
  'syms': { 'mov_13.movie_recommender': { 'mov_13.movie_recommender.get_movie_recs': ( 'movie_recommender.html#get_movie_recs',
                                                                                       'mov_13/movie_recommender.py'),
                                          'mov_13.movie_recommender.search_movies_n_recommend': ( 'movie_recommender.html#search_movies_n_recommend',
                                                                                                  'mov_13/movie_recommender.py')}}}